name: K6 Load Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 Test
        uses: grafana/run-k6-action@v1
        with:
          path: ./tests/hotstone-load.js
          flags: --vus 50 --duration 1m
